#!/bin/env python3

"""CLI to control CAX mirror motors for scanning its mirror."""

# from datetime import datetime
# import time
import numpy as np
import matplotlib.pyplot as plt

# from siriuspy.devices import CAXCtrl
# from motorkin import M1Kinematics
from caxscripts.motormov import (
    DeviceMove, CAXMirrorMove, CAXCausticMove, CAXSlitMove, SCAN_TYPES
    )


def scan_menu_select():
    """Select scan type from a menu."""
    print("Select scan (type a list of numbers separated by spaces):\n")
    for key, value in SCAN_TYPES.items():
        print(f"  {key} - {value} scan")

    caxdevs = list()
    while True:
        choices = input("\n Enter choice [1-9], 'q' to quit: ")
        if choices.lower() == 'q':
            print("Exiting... Done.")
            exit(0)
        choices = choices.strip().split()
        for choice in choices:
            if choice not in ['1', '2', '3', '4', '5', '6', '7', '8', '9']:
                print("Invalid choice."
                    " Please enter a number between 1 and 9.")
                break
        else:
            break

    for choice in choices:
        if choice in ['1', '2', '3', '4', '5']:
            caxdev = CAXMirrorMove()
        elif choice in ['6', '7']:
            caxdev = CAXCausticMove()
        else:
            caxdev = CAXSlitMove()
        caxdevs.append(caxdev)
    return set(choices), set(caxdevs)


def status_show(caxdev):
    """Show current status of the device."""
    print(f"\n##### {caxdev.devname} #####")
    status = caxdev.device_status()

    # DEBUG
    print(f"\n>>>\n DEBUG: status dict: {status} \n<<<\n")
    # END DEBUG

    for key, val in status.items():
        print(f"\n -- {key.replace('_', ' ').title()}:\n")
        for pv, v in val.items():
            print(f"  * {pv:15} ({v[1]:>8}) : {v[0]:10.4f}")
    print("\n#####\n")


def parameters_ask(scantype: str):
    """Get scan parameters from user."""
    st = SCAN_TYPES[scantype]
    print(f"###\n###  {st} scan parameters\n###\n")
    start  = float(input(f"Enter start {st} position/angle (urad): "))
    stop   = float(input(f"Enter stop {st} position/angle (urad): "))
    nsteps = float(input(f"Enter {st} number of steps: "))
    dtime  = float(input(
        "Enter dwell time at each position (seconds): "
        ))
    return start, stop, nsteps, dtime


def show_results(results, scantype: str):
    """Show scan results."""
    print("\n\n##### Scan Results #####\n")
    fig, ax = plt.subplots()
    ax.plot(results['position'], results['intensity'], marker='o')
    ax.set_xlabel('Position/Angle (urad)')
    ax.set_ylabel('Intensity (a.u.)')
    dt = SCAN_TYPES[scantype]
    ax.set_title(f'CAX {dt} Scan Results')
    plt.grid()
    plt.show()


def main():
    """Main function to run the CLI."""
    # DEBUG: Verify module origin
    # import siriuspy.devices.beamlines.mirror as mirror
    # print(f"\n[DEBUG] Mirror module loaded from: {mirror.__file__}\n")
    # END DEBUG

    # Initialize control.
    # caxctrl = CAXCtrl()
    # caxmov  = CAXMirrorMove(caxctrl)
    # m1kin   = M1Kinematics()

    # Current status.
    print("\n\n#####\n##### Carcará Scanning System\n#####\n")
    # motor_positions(caxmov)

    # Select scan type.
    scantype, caxdevs = scan_menu_select()

    # DEBUG: Show status of each device.
    # print(f"\n SCAN TYPES = {SCAN_TYPES}\n")
    # END DEBUG

    print("\n\n##### Current Status of Selected Devices #####")

    # print("Selected scan types:\n"
    #       f" {', '.join([SCAN_TYPES[st] for st in scantype])}\n")

    for caxdev in caxdevs:
        # print(f"\n--- {caxdev.devname} ---")
        status_show(caxdev)
        # print("\n-----------------------\n")
    return

    results  = DeviceMove.device_scan(scantype, caxdevs)

    # Show and/or record results.
    if results is not None:
        show_results(results, scantype)
        recres = input(" Do you want to save the results to a file? (y/n): ")
        if recres.lower() == 'y':
            filename = input(" Enter filename to save results"
                             " (e.g., scan_results.npz): ")
            np.savez(filename, **results)
            print(f" Results saved to {filename}.")
    else:
        print(" No results to show.")


if __name__ == "__main__":
    """."""
    main()
